[package]
name = "yukifile"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "yukifile"
path = "src/main.rs"

[lib]
name = "yukifile"
path = "src/lib.rs"

[dependencies]
blake3 = "1.8.7"
log = "0.4.34"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[dev-dependencies]

[build-dependencies]
tauri-build = { version = "2", features = [] }
